### ISSUE TITLE
10

### ISSUE THREAD

**Issue by dominuss-git** [sokol-forbes/course#10]
https://github.com/sokol-forbes/course/blob/8a4e4be10d48f3e8e069de6d982eb95592c21ae6/src/styles/scss.scss#L12-L14

```css

@media (min-width:960px) {
        font-size: 48px;
}
````

same but looks more pretty
